### ISSUE TITLE
QFJ does not wait for Logout reply when EndTime is reached

### ISSUE THREAD

**Issue by cristianmorex** [quickfix-j/quickfixj#244]
Good afternoon,

We are using QuickFix 2.2.0 and FIX4.2 messages version.

We configured our session.cnf with StartTime and EndTime. Our problem is when time is equal to EndTime, QuickFix sends logout message but doesn't wait to response and generates a reset event: Disconnecting: Session reset.

Could you help us?

Thank you, regards.

**Comment by chrjohn** [comment]
Can one of #244 and #243 be closed? Sounds like the same issue.
QFJ 2.2.0 is not released. Do you mean you tested this with the SNAPSHOT version or is it a typo?

However, I can confirm that this is a bug.

**Comment by cristianmorex** [comment]
Hi, thank you for your answer @chrjohn .
Yes, I could close #243. 

Sorry, we are using the version 2.1.1.
Do you know if the release 2.2.0 will fix this bug?

**Comment by chrjohn** [comment]
Hi @cristianmorex , up to yesterday (i.e. when you created this bug) I was not aware of this problem. But from  looking at the code I can confirm that what you describe is indeed happening.

When the Logout is sent, the `disconnect()` method is called afterwards which effectively resets all state flags, i.e also the `logoutSent` flag, so QFJ does not "know" that it has to wait for a Logout reply.

It might work to just set the Session to disabled instead, which will send a Logout and wait for a Logout to come back. But this of course needs to be implemented and tested.

So to answer your last question: QFJ 2.2.0 will not fix this bug since a fix has not been implemented yet. You could either wait that someone fixes this or give it a shot and submit a pull request to fix the problem. :)

Cheers,
Chris.

**Comment by hmendes85** [comment]
Hi, I'm also experiencing the logout issue mentioned by Christian. Thanks

**Comment by chrjohn** [comment]
Hi @hmendes85 , there already is a PR #312 that should fix this. However, we will need to check if it can be included in the next patch release or if it will have to wait for 3.0.0.
